# .swiftlint.yml

disabled_rules:
  - todo

opt_in_rules:
  - empty_count
  - closure_spacing
  - explicit_init
  - first_where
  - modifier_order
  - sorted_first_last
  - vertical_whitespace_closing_braces

line_length:
  warning: 120
  error: 150

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 40
  error: 60

identifier_name:
  min_length: 2
  max_length: 50

excluded:
  - .build
  - DerivedData
